# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicTacToe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TicTacToe
  pod 'Firebase/Core'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'TicTacToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TicTacToe-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
